sudo: required
language: go
go:
- 1.7
env:
  global:
  - LATEST_GO_VERSION="1.7"
  - secure: l9ConO+B9geFyuJe/Wvcx+Vf8XjiRYbiz/TNz7gmbBXoZp+9jUo8ruDIJrM+WNhVcTZJp4813RqlF8eOIavULWG4rlSdFxeTTRNj0mgN+/Oyj+s7lxWak9ietHYePbMQ93gzM0sJI+BmFUuA6259rNuZj7z892zqhU1FQbfm16TvoN0YNH3PIMx2COMeee6CGaktP5OjRruwj2GbMml2YUQwKZD2XvNqmgQY4uk/15RJ5nRB9qYUSU7dF2Hfj+QryQfQkO6YYX6N2CHzeevt449I/VH3qidzoNggdQcBxXCz3qCGYG2jlHB8Vr9TKBVu/KgWDb2uUBcz+QApGI/i7Tbol761tTgbeEZEHOYJNtwyVwBjhPMuIs4i1RRyPb7cQLAwANWI788LkqRiWJyXJ3rwvvbhG8olQOMzCvIlFKfNZGJwPf8BHj1LnoY0Dne1Se9I1LBygJCkd0so/h+3/cp3XlxTdNHBOs4Mxw/WGDvl418kibybvWu+SUGKACJ1yaqqWFYDEm9OAYCmGCtx8pbMefqehU9oFvU4gyLsMqh2xy7WDzHGv+nTKRJM1Cr8zHNm7x0oIUgMawHqmh0TAwrLEyLAZ7Qc40ZSSLJeVoN7hnk3pCKYJJ0x55UiiiQv+LzhTD9KeJsXfwxwvkPWRq9C5Rzg5oIs1TXi+yxvmTg=
  - secure: Jlyl8+A0jbrNeRGchsSPrIyqulu13mR7pQ+1mWZNyO120GSwn3CSQUdlp+aztspMZWPwiX5e+U7xezC5YM9OqRg3aeKsQ1kGb1t3CSsluCdfyQE03I+Dbp/4CtMIshAT51FcvW6V1Ly1zTkS+MTr1e5RRoKKW0p677WDVxbRNw2J6Tgdgv9degzNBvFFeqg+5AlZde0GUqnsm7H1IXsiO2zeu22wP2nO9MWZ8/ykDaxT/XLhC3FyStIXh/KZR/XYRGzbf8eAZxM25aT0fFd0Haae7aAqzSpLMZpzx6Lx9D75tc6xX/UELCtgX2oz8N/bdQzaCSaGBrDVPH+gMIAshF6tIHKMrWMtMhZtJLWG7BXc3kdcGFfBrM7JRLlcZDrSd8E7xSTA4Eni5AQsSlOizuL7nlCzFQN/6mhxisX0G9lHXKx3MFVTmBhSUw8+GymldAcHatKVndXDg2KqGoUscO9h6PDfQI1GuFIG+eG+bBbP2HKYpiYk+3FbpsgtVC9RpH3gSMnEUQgC55WnoCd8+UvzRpK+JpQVCaX3NVyXjcX17AzBEEhUMcvJfSx2JYwQGmfWNFVzFRFdCgol13c386ShUql66xZto2yH1sViFtk3izqq69FJuq7BUzhCCeDd0BsLKZ2Tivxs2zwchEcEayU0QegleU3wps/NZ2YsKes=
services:
- docker
after_success:
- source ./build/travis-utils.sh
- if is_travis_push_env; then docker login -u $DOCKER_USER -p $DOCKER_PASSWORD; fi
- if is_travis_push_env; then make image-quick; fi
- if is_travis_push_env; then make push; fi
- if is_travis_push_env; then make tag-latest; fi
- if is_travis_push_env; then make push-latest; fi
- if is_travis_push_env; then make perf-regression; fi
